---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: viewer
rules:
- apiGroups: ["*"]
  resources: ["deployments", "pods", "services", "configmaps",  "secrets"]
  verbs: ["get", "list", "watch"]