---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myapp
  namespace: 11-default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs
  resources:
    requests:
      storage: 5Gi